baseURL = 'http://matthewbarga.com'
languageCode = 'en-us'
title = 'Matthew Barga'
theme = 'archie'
# copyright = "© Athul"

# Code Highlight
#pygmentsstyle = "monokai"
pygmentsstyle = "gruvbox"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#paginate=3 # articles per page

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	#subtitle = "About me"
	favicon="favicon.png"
	CV="matthew_barga_cv.pdf"

# Main menu Items

[[menu.main]]
name = "About"
url = "/"
weight = 1

[[menu.main]]
name = "CV"
url = "/cv"
weight = 2

[[menu.main]]
name = "Contact"
url = "/contact"
weight = 3

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/mbarga"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://linkedin.com/in/matthewbarga"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/mbarga"

